     1|// Auto-generated by migrate-all-locales.ts
     2|import common from './common.json';
     3|import agentMode from './agentMode.json';
     4|import update from './update.json';
     5|import login from './login.json';
     6|import fileSelection from './fileSelection.json';
     7|import preview from './preview.json';
     8|import conversation from './conversation.json';
     9|import settings from './settings.json';
    10|import messages from './messages.json';
    11|import mcp from './mcp.json';
    12|import acp from './acp.json';
    13|import codex from './codex.json';
    14|import tools from './tools.json';
    15|import gemini from './gemini.json';
    16|import cron from './cron.json';
    17|import starOffice from './starOffice.json';
    18|import guid from './guid.json';
    19|import agent from './agent.json';
    20|import team from './team.json';
    21|import pet from './pet.json';
import solidai from './solidai.json';
    22|
    23|export default {
    24|  common,
    25|  agentMode,
    26|  update,
    27|  login,
    28|  fileSelection,
    29|  preview,
    30|  conversation,
    31|  settings,
    32|  messages,
    33|  mcp,
    34|  acp,
    35|  codex,
    36|  tools,
    37|  gemini,
    38|  cron,
    39|  starOffice,
    40|  guid,
    41|  agent,
    42|  team,
    43|  pet,
    44|};
    45|