// 变量覆盖清单（与 simple-theme/theme.css 对齐）
// 可按需扩展：primary-*, success-*, warning-*, danger-* 等色板

export const THEME_VARIABLE_KEYS = [
  // 背景
  '--color-bg-1',
  '--color-bg-2',
  '--color-bg-3',
  '--color-bg-4',
  '--color-bg-5',
  // 文本
  '--color-text-1',
  '--color-text-2',
  '--color-text-3',
  '--color-text-4',
  // 边框
  '--color-border-1',
  '--color-border-2',
  '--color-border-3',
  '--color-border-4',
  // 填充
  '--color-fill-1',
  '--color-fill-2',
  '--color-fill-3',
  '--color-fill-4',
  // 常用主色（可映射到 Arco token）
  '--primary-1',
  '--primary-2',
  '--primary-3',
  '--primary-4',
  '--primary-5',
  '--primary-6',
  '--primary-7',
  '--success-1',
  '--success-2',
  '--success-3',
  '--success-4',
  '--success-5',
  '--success-6',
  '--success-7',
  '--warning-1',
  '--warning-2',
  '--warning-3',
  '--warning-4',
  '--warning-5',
  '--warning-6',
  '--warning-7',
  '--danger-1',
  '--danger-2',
  '--danger-3',
  '--danger-4',
  '--danger-5',
  '--danger-6',
  '--danger-7',
  '--link-1',
  '--link-2',
  '--link-3',
  '--link-4',
  '--link-5',
  '--link-6',
  '--link-7',
  // 数据色板（示例，按需扩展）
  '--data-1',
  '--data-2',
  '--data-3',
  '--data-4',
  '--data-5',
  '--data-6',
  '--data-7',
  '--data-8',
  '--data-9',
  '--data-10',
  // 边框宽度
  '--border-1',
  '--border-2',
  '--border-3',
  // 圆角
  '--border-radius-none',
  '--border-radius-small',
  '--border-radius-medium',
  '--border-radius-large',
  '--border-radius-circle',
  // 阴影（示例）
  '--shadow-special',
  '--shadow1-center',
  '--shadow2-center',
];

export const FRIENDLY_LABELS: Record<string, string> = {
  '--color-bg-1': '主背景色',
  '--color-bg-2': '次级背景色',
  '--color-bg-3': '面板背景色',
  '--color-bg-4': '浅色背景',
  '--color-bg-5': '最浅背景',

  '--color-text-1': '主文字',
  '--color-text-2': '次文字',
  '--color-text-3': '弱文字',
  '--color-text-4': '提示文字',

  '--color-border-1': '边框-1',
  '--color-border-2': '边框-2',
  '--color-border-3': '边框-3',
  '--color-border-4': '边框-4',

  '--color-fill-1': '填充-1',
  '--color-fill-2': '填充-2',
  '--color-fill-3': '填充-3',
  '--color-fill-4': '填充-4',
  '--primary-1': '主色-浅1',
  '--primary-2': '主色-浅2',
  '--primary-3': '主色-浅3',
  '--primary-4': '主色-场景',
  '--primary-5': '主色-悬停',
  '--primary-6': '主色-默认',
  '--primary-7': '主色-按下',
  '--success-1': '成功-浅1',
  '--success-2': '成功-浅2',
  '--success-3': '成功-浅3',
  '--success-4': '成功-场景',
  '--success-5': '成功-悬停',
  '--success-6': '成功-默认',
  '--success-7': '成功-按下',
  '--warning-1': '警告-浅1',
  '--warning-2': '警告-浅2',
  '--warning-3': '警告-浅3',
  '--warning-4': '警告-场景',
  '--warning-5': '警告-悬停',
  '--warning-6': '警告-默认',
  '--warning-7': '警告-按下',
  '--danger-1': '危险-浅1',
  '--danger-2': '危险-浅2',
  '--danger-3': '危险-浅3',
  '--danger-4': '危险-场景',
  '--danger-5': '危险-悬停',
  '--danger-6': '危险-默认',
  '--danger-7': '危险-按下',
  '--link-1': '链接-浅1',
  '--link-2': '链接-浅2',
  '--link-3': '链接-浅3',
  '--link-4': '链接-场景',
  '--link-5': '链接-悬停',
  '--link-6': '链接-默认',
  '--link-7': '链接-按下',
  '--data-1': '数据-1',
  '--data-2': '数据-2',
  '--data-3': '数据-3',
  '--data-4': '数据-4',
  '--data-5': '数据-5',
  '--data-6': '数据-6',
  '--data-7': '数据-7',
  '--data-8': '数据-8',
  '--data-9': '数据-9',
  '--data-10': '数据-10',
  '--border-1': '边框宽度-1',
  '--border-2': '边框宽度-2',
  '--border-3': '边框宽度-3',
  '--border-radius-none': '圆角-无',
  '--border-radius-small': '圆角-小',
  '--border-radius-medium': '圆角-中',
  '--border-radius-large': '圆角-大',
  '--border-radius-circle': '圆角-全圆',
  '--shadow-special': '阴影-特殊',
  '--shadow1-center': '阴影-样式1',
  '--shadow2-center': '阴影-样式2',
};
