#!/usr/bin/env python3
"""
Generate final markdown report from analyst drafts.
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path


def read_insights(insights_path: Path) -> str:
    """Read insights markdown, return empty string if not found."""
    if not insights_path.exists():
        return ""
    return insights_path.read_text()


def extract_executive_summary(insights: str) -> str:
    """
    Extract executive summary from insights.

    Looks for ## Bottom Line section, or first paragraph.
    """
    if not insights:
        return ""

    # Try to find "Bottom Line" section
    if "## Bottom Line" in insights:
        lines = insights.split("\n")
        summary_lines = []
        in_bottom_line = False

        for line in lines:
            if line.startswith("## Bottom Line"):
                in_bottom_line = True
                continue
            elif in_bottom_line:
                if line.startswith("#"):  # Next section
                    break
                if line.strip():
                    summary_lines.append(line.strip())

        return " ".join(summary_lines)

    # Fallback: extract first paragraph after first heading
    lines = insights.split("\n")
    para = []
    found_heading = False

    for line in lines:
        if line.startswith("#"):
            found_heading = True
            continue
        if found_heading and line.strip():
            if line.startswith("#"):  # Next heading
                break
            para.append(line.strip())
        if found_heading and not line.strip() and para:  # End of paragraph
            break

    return " ".join(para[:3])  # First 3 lines max


def generate_report(drafts_dir: Path, symbol: str) -> str:
    """Generate final markdown report from all drafts."""
    report = f"# Investment Analysis: {symbol}\n\n"
    report += f"**Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}\n\n"
    report += "---\n\n"

    # Executive Summary
    report += "## Executive Summary\n\n"

    analysts = [
        ("macro", "Macroeconomic Analysis"),
        ("fundamentals", "Fundamental Analysis"),
        ("factors", "Factor Analysis"),
        ("technicals", "Technical Analysis"),
        ("valuation", "Valuation Analysis"),
        ("sentiment", "Sentiment Analysis"),
    ]

    for analyst_dir_name, analyst_title in analysts:
        insights_path = drafts_dir / analyst_dir_name / "insights.md"
        summary = extract_executive_summary(read_insights(insights_path))
        if summary:
            report += f"**{analyst_title}**: {summary}\n\n"

    report += "---\n\n"

    # Full Analysis Sections
    for analyst_dir_name, analyst_title in analysts:
        insights_path = drafts_dir / analyst_dir_name / "insights.md"
        insights = read_insights(insights_path)

        if insights:
            report += f"## {analyst_title}\n\n"
            report += insights
            report += "\n\n---\n\n"

    # Footer
    report += "## Methodology\n\n"
    report += "This report was generated by a multi-agent research system.\n\n"
    report += "**Agents**:\n"
    report += "- Macro Analyst: Classifies economic regime and sector implications\n"
    report += "- Fundamental Analyst: Analyzes financial statements and company quality\n"
    report += "- Factor Analyst: Calculates quantitative factor exposures\n"
    report += "- Technical Analyst: Identifies price trends and entry/exit points\n"
    report += "- Valuation Analyst: Estimates intrinsic value\n"
    report += "- Sentiment Analyst: Gauges market psychology from news and insider activity\n\n"

    return report


def main():
    parser = argparse.ArgumentParser(
        description="Generate final markdown report from analyst drafts"
    )
    parser.add_argument("--drafts", type=str, required=True,
                       help="Path to drafts directory")
    parser.add_argument("--symbol", type=str, required=True,
                       help="Stock symbol")
    parser.add_argument("--output", type=str, required=True,
                       help="Output markdown file path")

    args = parser.parse_args()

    drafts_dir = Path(args.drafts)
    if not drafts_dir.exists():
        print(f"Error: Drafts directory not found: {drafts_dir}", file=sys.stderr)
        return 1

    # Generate report
    report = generate_report(drafts_dir, args.symbol)

    # Write output
    with open(args.output, 'w') as f:
        f.write(report)

    print(f"Report generated: {args.output}")
    print(f"Length: {len(report)} characters")

    return 0


if __name__ == "__main__":
    sys.exit(main())
