#!/usr/bin/env npx ts-node
/**
 * i18n 迁移脚本
 * 将单一 JSON 文件拆分为模块化结构
 * 用法: npx ts-node scripts/migrate-i18n-locale.ts <locale>
 * 示例: npx ts-node scripts/migrate-i18n-locale.ts ja-JP
 */

import * as fs from 'fs';
import * as path from 'path';

// 模块列表（与 zh-CN 和 en-US 保持一致）
const MODULES = [
  'common',
  'agentMode',
  'update',
  'login',
  'fileSelection',
  'preview',
  'conversation',
  'settings',
  'messages',
  'mcp',
  'acp',
  'codex',
  'tools',
  'gemini',
  'cron',
  'guid',
  'agent',
];

const LOCALES_DIR = path.resolve(__dirname, '../src/renderer/i18n/locales');

function migrateLocale(locale: string): void {
  const sourceFile = path.join(LOCALES_DIR, `${locale}.json`);
  const targetDir = path.join(LOCALES_DIR, locale);

  // 检查源文件是否存在
  if (!fs.existsSync(sourceFile)) {
    console.error(`❌ 源文件不存在: ${sourceFile}`);
    process.exit(1);
  }

  // 创建目标目录
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
    console.log(`📁 创建目录: ${targetDir}`);
  }

  // 读取源 JSON
  const content = fs.readFileSync(sourceFile, 'utf-8');
  const data = JSON.parse(content);

  // 拆分并写入各模块
  let migratedModules = 0;
  for (const moduleName of MODULES) {
    if (data[moduleName] !== undefined) {
      const moduleFile = path.join(targetDir, `${moduleName}.json`);
      const moduleContent = JSON.stringify(data[moduleName], null, 2);
      fs.writeFileSync(moduleFile, moduleContent, 'utf-8');
      console.log(`  ✅ ${moduleName}.json`);
      migratedModules++;
    } else {
      // 创建空模块文件
      const moduleFile = path.join(targetDir, `${moduleName}.json`);
      fs.writeFileSync(moduleFile, '{}', 'utf-8');
      console.log(`  ⚠️ ${moduleName}.json (空)`);
    }
  }

  // 创建 index.ts
  const indexContent = generateIndexTs(locale);
  const indexFile = path.join(targetDir, 'index.ts');
  fs.writeFileSync(indexFile, indexContent, 'utf-8');
  console.log(`  📝 index.ts`);

  console.log(`\n✅ 迁移完成: ${migratedModules}/${MODULES.length} 个模块`);
}

function generateIndexTs(locale: string): string {
  const imports = MODULES.map(
    (m) => `import ${m} from './${m}.json';`
  ).join('\n');

  const exports = MODULES.join(', ');

  return `// Auto-generated by migrate-i18n-locale.ts
// Do not edit manually

${imports}

export default {
  ${exports.split(', ').join(',\n  ')},
};
`;
}

function deleteOldJson(locale: string): void {
  const sourceFile = path.join(LOCALES_DIR, `${locale}.json`);
  if (fs.existsSync(sourceFile)) {
    fs.unlinkSync(sourceFile);
    console.log(`🗑️ 已删除旧文件: ${sourceFile}`);
  }
}

// 主函数
function main(): void {
  const args = process.argv.slice(2);

  if (args.length === 0) {
    console.log('用法: npx ts-node scripts/migrate-i18n-locale.ts <locale> [--delete]');
    console.log('示例: npx ts-node scripts/migrate-i18n-locale.ts ja-JP');
    console.log('      npx ts-node scripts/migrate-i18n-locale.ts ja-JP --delete');
    process.exit(1);
  }

  const locale = args[0];
  const shouldDelete = args.includes('--delete');

  console.log(`\n🚀 开始迁移: ${locale}\n`);

  migrateLocale(locale);

  if (shouldDelete) {
    deleteOldJson(locale);
  }

  console.log('\n✨ 完成！\n');
}

main();
